### ISSUE TITLE
Existing 1+ year long members that upgrade are over charged

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-proration#20]
Originates from #501406 (mods only)

1. Member has a monthly level and has held it for longer than 1 year (only applies to those that have had one for this timeframe)
2. When upgrading to an annual plan, the initial payment is inflated due to the 'credit' being calculated into a negative. 

Adding a check to make sure that the credit can never be below $0 resolves this. 

Line 167~ we can add in

```
if( $credit < 0 || $days_passed > 365 ) {
   $credit = $morder->subtotal;
}
```

**Comment by dparker1005** [comment]
Resolved by #11
