### ISSUE TITLE
Chance cancellation to extend membership until the next payment date

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-proration#5]
It works this way for downgrades, but not full cancellations.

This gist will work as a work around:
https://www.paidmembershipspro.com/change-pmpro-membership-cancellation-to-set-expiration-date-for-next-payment-instead-of-cancelling-immediately/

But we should maybe do the same kind of functionality inside of this plugin.

**Comment by ideadude** [comment]
Might not be working for downgrades either. Need to look into it.

**Comment by dparker1005** [comment]
Closing as the Add On can currently be used, and this functionality will be merged into core in PMPro v3.0
